# Generated by Django 4.1 on 2022-10-01 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_review",
                to="profiles.profile",
                verbose_name="Agent being rated",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AddField(
            model_name="rating",
            name="rater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rating",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Providing the Rating",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Fair"),
                    (3, "Good"),
                    (4, "Very Good"),
                    (5, "Excellent"),
                ],
                help_text="1=Port, 2=Fair, 3=Good, 4=Very Good, 5=Excellent",
                null=True,
                verbose_name="Rating",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("rater", "agent")},
        ),
    ]
